export type ReqBody = {
  country?: string;
  course?: string;
  gpa?: number;
  bachelors?: string;
  target_university?: string;
  type?: string;
  query?: string;
  slug?: string;
};

async function callGroqWithFallback(prompt: string, systemPrompt?: string) {
  const API_KEY = process.env.GROQ_API_KEY || process.env.GROQ_AI_KEY || '';
  const API_URL = 'https://api.groq.com/openai/v1/chat/completions';

  if (!API_KEY) return null;

  const messages: any[] = [];
  messages.push({
    role: 'system',
    content: systemPrompt || 'You are a database system returning strictly valid JSON. Never output non-JSON text, key=value syntax, or prose outside JSON.'
  });
  messages.push({ role: 'user', content: prompt });

  // 1st attempt: standard json_object response format
  try {
    const res = await fetch(API_URL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${API_KEY}`,
      },
      body: JSON.stringify({
        model: 'llama-3.3-70b-versatile',
        messages,
        response_format: { type: 'json_object' }
      })
    });

    if (res.ok) {
      const data = await res.json();
      const content = data.choices?.[0]?.message?.content;
      if (content) {
        return JSON.parse(content);
      }
    } else {
      const errText = await res.text();
      console.warn('Groq initial call failed, proceeding to fallback:', errText);
    }
  } catch (e) {
    console.warn('Groq 1st attempt exception, proceeding to fallback:', e);
  }

  // 2nd attempt: plain text output, sanitize common LLM pseudo-syntax like `"pros=["` -> `"pros":[`
  try {
    const res = await fetch(API_URL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${API_KEY}`,
      },
      body: JSON.stringify({
        model: 'llama-3.3-70b-versatile',
        messages,
      })
    });

    if (res.ok) {
      const data = await res.json();
      const content = data.choices?.[0]?.message?.content || '';
      // Fix syntax errors such as "key=[" or "key={" generated by LLM
      const sanitized = content
        .replace(/"([a-zA-Z0-9_]+)=\[/g, '"$1": [')
        .replace(/"([a-zA-Z0-9_]+)=\{/g, '"$1": {')
        .replace(/"([a-zA-Z0-9_]+)="([^"]*)"/g, '"$1": "$2"');

      const match = sanitized.match(/(\{[\s\S]*\}|\[[\s\S]*\])/);
      if (match) {
        return JSON.parse(match[0]);
      }
    } else {
      console.error('Groq fallback call also failed:', await res.text());
    }
  } catch (e) {
    console.error('Groq fallback call exception:', e);
  }

  return null;
}

export async function fetchUniversityData(body: ReqBody) {
  const { country = 'Any', course = '', gpa = 0, bachelors = '', target_university = '', type = '', query = '', slug = '' } = body;

  let prompt = '';
  let systemPrompt = 'You are a higher education database assistant. Output ONLY valid, strict, clean JSON object.';

  if (type === 'university_detail') {
    prompt = `Provide a comprehensive, real-world detailed profile for the university: "${query || slug}". 
    Location context: ${country}. Program interest: ${course}.
    
    CRITICAL: For the "websiteDomain" field, provide ONLY the real official domain of this university (e.g. "ed.ac.uk" for University of Edinburgh, "mit.edu" for MIT, "ox.ac.uk" for Oxford). Do NOT invent domains.

    Return a single JSON object with EXACTLY these key-value pairs (use double quotes for all keys and strings, and standard colons between key and value):
    {
      "name": "Full Official Name of the University",
      "shortName": "Common Short Name",
      "loc": "City, State/Province",
      "country": "Country",
      "countryCode": "2-letter ISO country code",
      "websiteDomain": "ed.ac.uk",
      "founded": 1900,
      "rank": 123,
      "rankBy": "QS World Rankings",
      "acceptanceRate": 15,
      "tuition": 35000,
      "currency": "USD",
      "description": "Rich history and academic standing.",
      "programs": [
        { "name": "M.S. in Computer Science", "degree": "Master's", "duration": "2 Years", "tuition": "$35,000/year", "icon": "code" }
      ],
      "requirements": { "gpa": "3.5/4.0 or 8.0/10", "ielts": "7.0", "toefl": "100+", "gre": "Optional" },
      "stats": { "totalStudents": "25,000+", "internationalStudents": "22%", "facultyRatio": "14:1", "employmentRate": "94%", "researchOutput": "Very High", "avgSalary": "$110k" },
      "loan": true,
      "pros": ["Top faculty", "Great campus"],
      "facilities": [{ "name": "Robotics Lab", "icon": "smart_toy" }],
      "funFacts": ["Fact 1", "Fact 2"],
      "whyStudyHere": ["Reason 1", "Reason 2"],
      "notableAlumni": [{ "name": "Full Name", "role": "Role description" }]
    }`;
  } else if (type === 'course') {
    systemPrompt = 'You are a course database assistant. Output ONLY a valid JSON object with a "courses" array.';
    prompt = `Search for courses/majors matching "${query || course}". 
    Return a JSON object: { "courses": ["Course 1", "Course 2"] }`;
  } else {
    if (query && query.trim().length > 0) {
      prompt = `Return a JSON object { "universities": [...] } with up to 25 real universities matching "${query}" in ${country || 'any country'}.
      Include: name, loc, country, rank, accept, tuition, loan (true), slug, website.`;
    } else {
      prompt = `Return a JSON object { "universities": [...] } with 25 real universities for ${course || 'Higher Education'} in ${country}.
      Include: name, loc, country, rank, accept, tuition, min_gpa, min_ielts, min_toefl, courses, loan (true), slug, website.`;
    }
  }

  const parsed = await callGroqWithFallback(prompt, systemPrompt);

  if (parsed) {
    if (type === 'university_detail') {
      const domain = (parsed.websiteDomain || parsed.website || '').replace(/^https?:\/\//, '').replace(/^www\./, '').replace(/\/$/, '');

      parsed.website = domain ? `https://www.${domain}` : (parsed.website || '');
      parsed.logo = domain ? `https://logo.clearbit.com/${domain}` : (parsed.logo || '');

      const countryKey = (parsed.country || country || '').toLowerCase();
      const HERO_IMAGES: Record<string, string> = {
        'united kingdom': 'https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=1600&q=80',
        'uk': 'https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=1600&q=80',
        'usa': 'https://images.unsplash.com/photo-1562774053-701939374585?w=1600&q=80',
        'united states': 'https://images.unsplash.com/photo-1562774053-701939374585?w=1600&q=80',
        'canada': 'https://images.unsplash.com/photo-1580537659466-0a9bfa916a54?w=1600&q=80',
        'australia': 'https://images.unsplash.com/photo-1523482580672-f109ba8cb9be?w=1600&q=80',
        'germany': 'https://images.unsplash.com/photo-1597672890275-702a4953ff1f?w=1600&q=80',
        'ireland': 'https://images.unsplash.com/photo-1590089415225-401ed6f9db8e?w=1600&q=80',
        'france': 'https://images.unsplash.com/photo-1549144511-f099e773c147?w=1600&q=80',
        'singapore': 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=1600&q=80',
      };
      const CAMPUS_IMAGES: Record<string, string[]> = {
        'united kingdom': [
          'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&q=80',
          'https://images.unsplash.com/photo-1580537659466-0a9bfa916a54?w=800&q=80',
          'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=800&q=80',
        ],
        'uk': [
          'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&q=80',
          'https://images.unsplash.com/photo-1580537659466-0a9bfa916a54?w=800&q=80',
          'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=800&q=80',
        ],
        'usa': [
          'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=800&q=80',
          'https://images.unsplash.com/photo-1519452635265-7b1fbfd1e4e0?w=800&q=80',
          'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80',
        ],
        'united states': [
          'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=800&q=80',
          'https://images.unsplash.com/photo-1519452635265-7b1fbfd1e4e0?w=800&q=80',
          'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80',
        ],
      };
      const defaultHero = 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=1600&q=80';
      const defaultCampus = [
        'https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80',
        'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=800&q=80',
        'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&q=80',
      ];

      parsed.heroImage = parsed.heroImage || HERO_IMAGES[countryKey] || defaultHero;
      parsed.campusImages = (parsed.campusImages && parsed.campusImages.length > 0)
        ? parsed.campusImages
        : (CAMPUS_IMAGES[countryKey] || defaultCampus);

      // Ensure pros is an array
      if (typeof parsed.pros === 'string') {
        parsed.pros = [parsed.pros];
      }

      return { university: parsed };
    }
    if (type === 'course') return { results: Array.isArray(parsed) ? parsed : (parsed.courses || parsed.results || []) };
    return { universities: parsed.universities || parsed.results || [] };
  }

  // Fallback return empty structure if AI fails
  if (type === 'university_detail') return { university: null };
  if (type === 'course') return { results: [] };
  return { universities: [] };
}